Update patch set 2
Patch Set 2: Code-Review-1

(1 comment)

see comments; i tried to fix it but it was rejected:

remote: Processing changes: refs: 1, done
To ssh://gerrit.onap.org:29418/ccsdk/distribution
 ! [remote rejected] HEAD -> refs/for/kohn%topic=131974 (commit 072d8b0: not Signed-off-by author/committer/uploader in message footer)
error: failed to push some refs to 'ssh://thmsdt@gerrit.onap.org:29418/ccsdk/distribution'

Patch-set: 2
Reviewer: Gerrit User 3091 <3091@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1